###########################################################################
# Launch installation script based on OS
###########################################################################

- name: Run Windows-specific tasks
  ansible.builtin.import_tasks: windows.yml
  vars:
    effective_version: "{{ version }}"
    product_name: "{{ pkg_name }}"
    download_url: "{{ windows_url }}"
    major_ver: "{{ version_major }}"
    installer: "{{ win_installer_name }}"
    arguments: "{{ win_installer_args }}"
  when: ansible_os_family == "Windows"

- name: Run Linux-specific tasks
  ansible.builtin.debug:
    msg: "{{ pkg_name }} can only be installed on Windows OS"
  when:
    - ansible_os_family != "Windows"
